/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {},
    fontFamily: {
      sans: [
        "-apple-system",
        "BlinkMacSystemFont",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
        "Segoe UI",
        "PingFang SC",
        "HarmonyOS_Regular",
        "Hiragino Sans GB",
        "Microsoft YaHei",
        "Helvetica Neue",
        "Helvetica",
        "Source Han Sans SC",
        "Noto Sans CJK SC",
        "WenQuanYi Micro Hei",
        "Arial",
        "sans-serif",
      ],
      serif: [
        "STZhongsong",
        "STSong",
        "Noto Serif CJK",
        "Noto Serif SC",
        "PMingLiu",
        "SimSun",
        "WenQuanYi Bitmap Song",
        "Times New Roman",
        "Times",
        "serif",
        "Apple Color Emoji",
        "Segoe UI Emoji",
        "Segoe UI Symbol",
      ],
    },
  },
  plugins: [require("@tailwindcss/forms")],
};
